CREATE TABLE transactions (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 external_id VARCHAR(64) NOT NULL UNIQUE,
 booked_on DATE NOT NULL,
 merchant VARCHAR(100) NOT NULL,
 category VARCHAR(24) NOT NULL CHECK (category IN ('FOOD','TRANSPORT','HOUSING','SHOPPING','OTHER')),
 amount DECIMAL(12,2) NOT NULL CHECK (amount > 0),
 currency VARCHAR(3) NOT NULL CHECK (currency = 'CAD')
);
CREATE INDEX idx_transactions_date ON transactions(booked_on);
CREATE INDEX idx_transactions_category ON transactions(category);
INSERT INTO transactions (external_id,booked_on,merchant,category,amount,currency) VALUES
('DEMO-001','2026-09-01','Maple Market','FOOD',48.25,'CAD'),
('DEMO-002','2026-09-02','City Transit','TRANSPORT',12.50,'CAD'),
('DEMO-003','2026-09-03','Northside Books','SHOPPING',35.00,'CAD');
